spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: ad-service
          uri: lb://AD-SERVICE
          predicates:
            - Path=/api/v1/ads/**
        - id: ad-package-service
          uri: lb://AD-PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/adPackages/**

server:
  port: 8080
